In [1]:
from google.colab import files
uploaded = files.upload()

Saving Ganjil.csv to Ganjil.csv

In [2]:
import pandas as pd

# Ganti nama file sesuai file kamu
df = pd.read_csv('Ganjil.csv')

# Lihat data
df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                   No;Berita
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...   KPK Bakal Siapkan SP3 :) !!!
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                                           NaN
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                                           NaN

1. Text Cleaning (Pembersihan Teks)

In [3]:
import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'http\S+', '', text)  # hapus URL
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # hapus angka & simbol
    text = re.sub(r'\s+', ' ', text).strip()  # hapus spasi berlebih
    return text

# Fix for the KeyError: 'Berita' due to incorrect CSV parsing
# If 'No;Berita' column exists, extract the 'Berita' part.
if 'No;Berita' in df.columns:
    # Use str.partition to safely get the part after the first semicolon
    # The partition method returns a DataFrame, so we access the third column directly by index [2]
    df['Berita_content'] = df['No;Berita'].astype(str).str.partition(';')[2]
    df['cleaning'] = df['Berita_content'].apply(clean_text)
    df[['Berita_content', 'cleaning']].head()
elif 'Berita' in df.columns:
    # If 'Berita' column already exists (e.g., if the CSV reading was fixed elsewhere),
    # proceed with the original logic.
    df['cleaning'] = df['Berita'].apply(clean_text)
    df[['Berita', 'cleaning']].head()
else:
    # Handle case where neither expected column is found (e.g., different column names)
    print("Error: Neither 'Berita' nor 'No;Berita' column found. Please check your DataFrame columns.")
    print("Available columns:", df.columns.tolist())

In [7]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Pastikan sudah mendownload resource NLTK yang diperlukan
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Tambahkan baris ini untuk mengunduh resource yang hilang

def clean_text(text):
    # 1. Mengubah teks menjadi lowercase (huruf kecil)
    text = text.lower()

    # 2. Menghapus URL (jika ada)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 3. Menghapus karakter spesial, angka, dan emoji
    # Kita hanya menyisakan huruf a-z
    text = re.sub(r'[^a-z\s]', '', text)

    # 4. Menghapus tanda baca (punctuation)
    text = text.translate(str.maketrans('', '', string.punctuation))

    # 5. Tokenisasi (memecah kalimat menjadi kata)
    tokens = word_tokenize(text)

    # 6. Menghapus Stopwords (kata umum yang kurang bermakna seperti 'yang', 'di', 'ke')
    stop_words = set(stopwords.words('indonesian'))
    # Opsional: Tambahkan kata spesifik yang ingin dibuang (misal: 'kompascom')
    additional_stop_words = {'kompascom', 'baca', 'juga'}
    stop_words.update(additional_stop_words)

    filtered_text = [word for word in tokens if word not in stop_words]

    # Menggabungkan kembali menjadi satu string
    return " ".join(filtered_text)

# Input Kalimat
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

cleaned_text = clean_text(raw_text)

print("--- Teks Sebelum Cleaning ---")
print(raw_text)
print("\n--- Teks Sesudah Cleaning ---")
print(cleaned_text)

--- Teks Sebelum Cleaning ---

JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!


--- Teks Sesudah Cleaning ---
jakarta komisi pemberantasan korupsi kpk nama pengusaha rokok khairul umam alias haji her tercantum dokumen ditemukan penyidik menggeledah kantor direktorat jenderal bea cukai djbc plt direktur penyidikan kpk achmad taufik husein termuat alasan kpk memanggil haji her saksi terkait dugaan korupsi lingkungan djbc haji her hasil penggeledahan temukan proses penyidikan kantor ditjen bea cukai dokumendokumen ocoy kasi intelijen djbc orlando hamonangan si tersangka taufik gedung merah putih jakarta senin analisisanalisis situlah ditemukan namanama pengusaha rokok suryo haji her sambung tersangka siman bahar meninggal dunia kpk siapkan sp

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

2. TOKENIZATION

In [6]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

df['tokenizing'] = df['cleaning'].apply(word_tokenize)

df[['cleaning', 'tokenizing']].head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

                                                                                                                                                                                                                                                                                                                                                                                                                              cleaning  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN
                                                                                                                                                                                                                                                                                                                                                                           NaN

                                                                                                                                                                                                                                                                                                                                                                                                                              tokenizing
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                        []

In [8]:
kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
pisah = kalimat.split()
print(pisah)

['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

3. NORMALIZATION

In [9]:
# contoh kamus sederhana
normalisasi = {
    "gk": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "kpk": "komisi pemberantasan korupsi"
}

def normalize_text(tokens):
    return [normalisasi.get(word, word) for word in tokens]

df['normalization'] = df['tokenizing'].apply(normalize_text)

df[['tokenizing', 'normalization']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              tokenizing  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                        []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                        []

                                                                                                                                                                                                                                                                                                                                                                                                                              normalization
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

In [10]:
import re

def normalize_text(text):
    # Mapping normalisasi: "Kata Tidak Baku/Singkatan": "Kata Baku"
    normalization_dict = {
        "kpk": "komisi pemberantasan korupsi",
        "djbc": "direktorat jenderal bea cukai",
        "plt": "pelaksana tugas",
        "ditjen": "direktorat jenderal",
        "sp3": "surat perintah penghentian penyidikan",
        "kasi": "kepala seksi"
    }

    # 1. Kecilkan huruf terlebih dahulu agar match dengan dictionary
    text = text.lower()

    # 2. Tokenisasi sederhana untuk mencocokkan kata per kata
    words = text.split()

    # 3. Proses penggantian kata
    normalized_words = []
    for word in words:
        # Menghapus tanda baca yang menempel pada kata (misal: "djbc.")
        clean_word = word.strip(string.punctuation)

        if clean_word in normalization_dict:
            # Ganti dengan versi panjangnya
            replacement = normalization_dict[clean_word]
            normalized_words.append(replacement)
        else:
            normalized_words.append(word)

    return " ".join(normalized_words)

# Contoh penggunaan dengan teks yang sudah dibersihkan sedikit (atau teks asli)
raw_text = "Plt Direktur Penyidikan KPK mengatakan ada dokumen di kantor DJBC terkait tersangka."

normalized_result = normalize_text(raw_text)

print("--- Sebelum Normalisasi ---")
print(raw_text)
print("\n--- Sesudah Normalisasi ---")
print(normalized_result)

--- Sebelum Normalisasi ---
Plt Direktur Penyidikan KPK mengatakan ada dokumen di kantor DJBC terkait tersangka.

--- Sesudah Normalisasi ---
pelaksana tugas direktur penyidikan komisi pemberantasan korupsi mengatakan ada dokumen di kantor direktorat jenderal bea cukai terkait tersangka.

4. Stopword Removal

In [11]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('indonesian'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['stopword'] = df['normalization'].apply(remove_stopwords)

df[['normalization', 'stopword']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                                                                                                                                                                                                                                                                                                                                                                                                              normalization  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

                                                                                                                                                                                                                                                                                                                                                                                                                              stopword
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

In [12]:
!pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
import re

# 1. Inisialisasi Factory Stopword Sastrawi
factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

# 2. Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

# 3. Pre-processing sederhana (Lowercasing)
# Stopword removal bekerja lebih baik jika teks sudah dalam huruf kecil
clean_text = raw_text.lower()

# 4. Proses Penghapusan Stopwords
result = stopword_remover.remove(clean_text)

print("--- Teks Setelah Stopword Removal ---")
print(result)

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.6 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1
--- Teks Setelah Stopword Removal ---

jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her tercantum dokumen ditemukan penyidik menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her saksi terkait kasus dugaan korupsi lingkungan djbc. “haji her, kembali, jadi hasil penggeledahan temukan proses penyidikan kantor ditjen bea cukai ada beberapa dokumen-dokumen dibuat ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

5. Case Folding

In [13]:
def case_folding(tokens):
    return [word.lower() for word in tokens]

df['casefolding'] = df['stopword'].apply(case_folding)

df[['stopword', 'casefolding']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              stopword  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

                                                                                                                                                                                                                                                                                                                                                                                                                              casefolding
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...          []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                         []

In [14]:
#import word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

tokens = nltk.tokenize.word_tokenize(kalimat)
print(tokens)

['JAKARTA', ',', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(', 'KPK', ')', 'mengatakan', ',', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(', 'DJBC', ')', '.', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan', ',', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC', '.', '“', 'Haji', 'Her', ',', 'saya', 'kembali', ',', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(', 'Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan', ')', 'si', 'tersangka', 'ini', ',', '”', 'kata', 'Taufik', ',', 'di', 'Gedung', 'Merah', 'Putih', ',', 'Jakarta', ',', 'Senin', '(', '13/4/2026', ')', '.', '“', 'Kemudian', 'kita', 'analisis-analisis', '.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok', '.', 'Suryo', 'termasuk', 'Haji', 'Her', ',', '”', 'sambung', 'dia', '.', 'Baca', 'juga', ':', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia', ',', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':', ')', '!', '!', '!']

In [15]:
from nltk.tokenize import word_tokenize
import string

kalimat = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"

kalimat = kalimat.translate(str.maketrans('', '', string.punctuation)).lower()
__builtins__.print(kalimat)

jakarta kompascom  komisi pemberantasan korupsi kpk mengatakan nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai djbc plt direktur penyidikan kpk achmad taufik husein mengatakan termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc “haji her saya kembali jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumendokumen yang dibuat oleh ocoy kasi intelijen djbc orlando hamonangan si tersangka ini” kata taufik di gedung merah putih jakarta senin 1342026 “kemudian kita analisisanalisis di situlah ditemukan beberapa namanama pengusaha rokok suryo termasuk haji her” sambung dia baca juga tersangka siman bahar meninggal dunia kpk bakal siapkan sp3

In [16]:
# Teks asli
raw_text = """
JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
"""

def case_folding(text):
    # Menggunakan fungsi bawaan Python .lower()
    return text.lower()

# Eksekusi
folded_text = case_folding(raw_text)

print("--- Hasil Case Folding ---")
print(folded_text)

--- Hasil Case Folding ---

jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

6. Stemming

In [17]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

In [18]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemming'] = df['casefolding'].apply(stemming)

df[['casefolding', 'stemming']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              casefolding  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...          []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                         []

                                                                                                                                                                                                                                                                                                                                                                                                                              stemming
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

In [19]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemming'] = df['casefolding'].apply(stemming)

df[['casefolding', 'stemming']].head()

                                                                                                                                                                                                                                                                                                                                                                                                                              casefolding  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...          []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                         []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                         []

                                                                                                                                                                                                                                                                                                                                                                                                                              stemming
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

In [20]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

kata = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

for k in kata:
    print(k, ":", ps.stem(k))

JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!! : jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!

In [21]:
from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()

words = ["JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"]

stemmed_words = [porter_stemmer.stem(word) for word in words]

print("Original words:", words)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!']
Stemmed words: ['jakarta, kompas.com - komisi pemberantasan korupsi (kpk) mengatakan, nama pengusaha rokok khairul umam alias haji her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor direktorat jenderal bea cukai (djbc). plt direktur penyidikan kpk achmad taufik husein mengatakan, termuat tersebut menjadi alasan kpk memanggil haji her sebagai saksi terkait kasus dugaan korupsi di lingkungan djbc. “haji her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor ditjen bea cukai itu ada beberapa dokumen-dokumen yang dibuat oleh ocoy (kasi intelijen djbc orlando hamonangan) si tersangka ini,” kata taufik, di gedung merah putih, jakarta, senin (13/4/2026). “kemudian kita analisis-analisis. di situlah ditemukan beberapa nama-nama pengusaha rokok. suryo termasuk haji her,” sambung dia. baca juga: tersangka siman bahar meninggal dunia, kpk bakal siapkan sp3 :) !!!']

In [22]:
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer (language='english')

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']
Stemmed words: ['jakarta,', 'kompas.com', '-', 'komisi', 'pemberantasan', 'korupsi', '(kpk)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'khairul', 'umam', 'alia', 'haji', 'her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'direktorat', 'jender', 'bea', 'cukai', '(djbc).', 'plt', 'direktur', 'penyidikan', 'kpk', 'achmad', 'taufik', 'husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'kpk', 'memanggil', 'haji', 'her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'djbc.', '“haji', 'her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'prose', 'penyidikan', 'di', 'kantor', 'ditjen', 'bea', 'cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'ocoy', '(kasi', 'intelijen', 'djbc', 'orlando', 'hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'taufik,', 'di', 'gedung', 'merah', 'putih,', 'jakarta,', 'senin', '(13/4/2026).', '“kemudian', 'kita', 'analisis-analisis.', 'di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'suryo', 'termasuk', 'haji', 'her,”', 'sambung', 'dia.', 'baca', 'juga:', 'tersangka', 'siman', 'bahar', 'meningg', 'dunia,', 'kpk', 'bakal', 'siapkan', 'sp3', ':)', '!!!']

In [23]:
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

words_to_stem = ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']

stemmed_words = [stemmer.stem(word) for word in words_to_stem]

print("Original words:", words_to_stem)

print("Stemmed words:", stemmed_words)

Original words: ['JAKARTA,', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(KPK)', 'mengatakan,', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(DJBC).', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan,', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC.', '“Haji', 'Her,', 'saya', 'kembali,', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'proses', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan)', 'si', 'tersangka', 'ini,”', 'kata', 'Taufik,', 'di', 'Gedung', 'Merah', 'Putih,', 'Jakarta,', 'Senin', '(13/4/2026).', '“Kemudian', 'kita', 'analisis-analisis.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok.', 'Suryo', 'termasuk', 'Haji', 'Her,”', 'sambung', 'dia.', 'Baca', 'juga:', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia,', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':)', '!!!']
Stemmed words: ['jakarta,', 'kompas.com', '-', 'komis', 'pemberantas', 'korups', '(kpk)', 'mengatakan,', 'nam', 'pengusah', 'rokok', 'khair', 'umam', 'alia', 'haj', 'her', 'ad', 'tercant', 'dalam', 'dokum', 'yang', 'ditemuk', 'penyidik', 'saat', 'menggeledah', 'kant', 'direkt', 'jend', 'bea', 'cuka', '(djbc).', 'plt', 'direkt', 'penyidik', 'kpk', 'achmad', 'taufik', 'husein', 'mengatakan,', 'termu', 'tersebut', 'menjad', 'alas', 'kpk', 'memanggil', 'haj', 'her', 'sebaga', 'saks', 'terkait', 'kas', 'duga', 'korups', 'di', 'lingkung', 'djbc.', '“haji', 'her,', 'say', 'kembali,', 'jad', 'hasil', 'penggeledah', 'yang', 'kit', 'temuk', 'di', 'pros', 'penyidik', 'di', 'kant', 'dits', 'bea', 'cuka', 'itu', 'ad', 'beberap', 'dokumen-dokum', 'yang', 'dibu', 'oleh', 'ocoy', '(kasi', 'intelid', 'djbc', 'orlando', 'hamonangan)', 'si', 'tersangk', 'ini,”', 'kat', 'taufik,', 'di', 'gedung', 'merah', 'putih,', 'jakarta,', 'senin', '(13/4/2026).', '“kemudian', 'kit', 'analisis-analisis.', 'di', 'situlah', 'ditemuk', 'beberap', 'nama-nam', 'pengusah', 'rokok.', 'suryo', 'termasuk', 'haj', 'her,”', 'sambung', 'dia.', 'bac', 'juga:', 'tersangk', 'sim', 'bah', 'mening', 'dunia,', 'kpk', 'bak', 'siapk', 'sp3', ':)', '!!!']

7. Lemmatization

In [24]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatization'] = df['stemming'].apply(lemmatization)

df[['stemming', 'lemmatization']].head()

[nltk_data] Downloading package wordnet to /root/nltk_data...

                                                                                                                                                                                                                                                                                                                                                                                                                              stemming  \
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...       []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                      []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                      []

                                                                                                                                                                                                                                                                                                                                                                                                                              lemmatization
1;JAKARTA                                          KOMPAS.com - Komisi Pemberantasan Korupsi (KPK)... nama pengusaha rokok Khairul Umam alias Haji He... termuat tersebut menjadi alasan KPK memanggil H... saya kembali jadi hasil penggeledahan yang kita temukan di p... ” kata Taufik di Gedung Merah Putih Jakarta Senin (13/4/2026). “Kemudian kita analisis-anal... ” sambung dia. Baca juga: Tersangka Siman Bahar...            []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;Sumber: https://nasional.kompas.com/read/2026/... NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
;                                                  NaN                                                NaN                                                NaN                                                NaN          NaN                                                NaN           NaN                   NaN     NaN                                                NaN                                                           []
                                                                                                                                                                                                                                                                                                                                                                           NaN                                                           []

In [25]:
from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
text = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(text)

lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

print(f"Original Text: {text}")

print(f"Lemmatized Words: {lemmatized_words}")

Original Text: JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
Lemmatized Words: ['JAKARTA', ',', 'KOMPAS.com', '-', 'Komisi', 'Pemberantasan', 'Korupsi', '(', 'KPK', ')', 'mengatakan', ',', 'nama', 'pengusaha', 'rokok', 'Khairul', 'Umam', 'alias', 'Haji', 'Her', 'ada', 'tercantum', 'dalam', 'dokumen', 'yang', 'ditemukan', 'penyidik', 'saat', 'menggeledah', 'kantor', 'Direktorat', 'Jenderal', 'Bea', 'Cukai', '(', 'DJBC', ')', '.', 'Plt', 'Direktur', 'Penyidikan', 'KPK', 'Achmad', 'Taufik', 'Husein', 'mengatakan', ',', 'termuat', 'tersebut', 'menjadi', 'alasan', 'KPK', 'memanggil', 'Haji', 'Her', 'sebagai', 'saksi', 'terkait', 'kasus', 'dugaan', 'korupsi', 'di', 'lingkungan', 'DJBC', '.', '“', 'Haji', 'Her', ',', 'saya', 'kembali', ',', 'jadi', 'hasil', 'penggeledahan', 'yang', 'kita', 'temukan', 'di', 'prose', 'penyidikan', 'di', 'kantor', 'Ditjen', 'Bea', 'Cukai', 'itu', 'ada', 'beberapa', 'dokumen-dokumen', 'yang', 'dibuat', 'oleh', 'Ocoy', '(', 'Kasi', 'Intelijen', 'DJBC', 'Orlando', 'Hamonangan', ')', 'si', 'tersangka', 'ini', ',', '”', 'kata', 'Taufik', ',', 'di', 'Gedung', 'Merah', 'Putih', ',', 'Jakarta', ',', 'Senin', '(', '13/4/2026', ')', '.', '“', 'Kemudian', 'kita', 'analisis-analisis', '.', 'Di', 'situlah', 'ditemukan', 'beberapa', 'nama-nama', 'pengusaha', 'rokok', '.', 'Suryo', 'termasuk', 'Haji', 'Her', ',', '”', 'sambung', 'dia', '.', 'Baca', 'juga', ':', 'Tersangka', 'Siman', 'Bahar', 'Meninggal', 'Dunia', ',', 'KPK', 'Bakal', 'Siapkan', 'SP3', ':', ')', '!', '!', '!']

In [26]:
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet # Import wordnet for POS tags
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

lemmatizer = WordNetLemmatizer()
sentence = "JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!"
tokens = word_tokenize(sentence)
tagged_tokens = pos_tag(tokens)

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return 'a'
    elif tag.startswith('V'):
        return 'v'
    elif tag.startswith('N'):
        return 'n'
    elif tag.startswith('R'):
        return 'r'
    else:
        return 'n'

lemmatized_sentence = []
for word, tag in tagged_tokens:
    lemmatized_sentence.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))

print(f"Original Sentence: {sentence}")
print(f"Lemmatized Sentence: {' '.join(lemmatized_sentence)}")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

Original Sentence: JAKARTA, KOMPAS.com - Komisi Pemberantasan Korupsi (KPK) mengatakan, nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai (DJBC). Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan, termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC. “Haji Her, saya kembali, jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy (Kasi Intelijen DJBC Orlando Hamonangan) si tersangka ini,” kata Taufik, di Gedung Merah Putih, Jakarta, Senin (13/4/2026). “Kemudian kita analisis-analisis. Di situlah ditemukan beberapa nama-nama pengusaha rokok. Suryo termasuk Haji Her,” sambung dia. Baca juga: Tersangka Siman Bahar Meninggal Dunia, KPK Bakal Siapkan SP3 :) !!!
Lemmatized Sentence: JAKARTA , KOMPAS.com - Komisi Pemberantasan Korupsi ( KPK ) mengatakan , nama pengusaha rokok Khairul Umam alias Haji Her ada tercantum dalam dokumen yang ditemukan penyidik saat menggeledah kantor Direktorat Jenderal Bea Cukai ( DJBC ) . Plt Direktur Penyidikan KPK Achmad Taufik Husein mengatakan , termuat tersebut menjadi alasan KPK memanggil Haji Her sebagai saksi terkait kasus dugaan korupsi di lingkungan DJBC . “ Haji Her , saya kembali , jadi hasil penggeledahan yang kita temukan di proses penyidikan di kantor Ditjen Bea Cukai itu ada beberapa dokumen-dokumen yang dibuat oleh Ocoy ( Kasi Intelijen DJBC Orlando Hamonangan ) si tersangka ini , ” kata Taufik , di Gedung Merah Putih , Jakarta , Senin ( 13/4/2026 ) . “ Kemudian kita analisis-analisis . Di situlah ditemukan beberapa nama-nama pengusaha rokok . Suryo termasuk Haji Her , ” sambung dia . Baca juga : Tersangka Siman Bahar Meninggal Dunia , KPK Bakal Siapkan SP3 : ) ! ! !